/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
fun problem2() {
    var prev = 1
    var current = 2
    var sum = 2
    while (current < 4_000_000) {
        val next = prev + current
        prev = current
        current = next
        if (current % 2 == 0) {
            sum += current
        }
    }
    println("Result: $sum")
    assert(sum == 4_613_732)
}